# Generated by Django 2.2.1 on 2019-07-03 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('matricula', models.IntegerField(null=True)),
                ('rfid', models.CharField(max_length=254, null=True)),
                ('delete', models.BooleanField(default=True)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'Alumno',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete', models.BooleanField(default=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora', models.DateField(default=datetime.date.today)),
                ('id_Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.Alumno')),
            ],
            options={
                'db_table': 'Asistencia',
            },
        ),
    ]
